version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=production
    env_file:
      - .env
    depends_on:
      - neo4j
    volumes:
      - ./src:/app/src
      - ./static:/app/static

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password  # Change in production
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
